- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "imu_raw"
  gz_topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "ground_truth_odom"
  gz_topic_name: "/model/Elkapod/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/legs/leg1_fsr"
  gz_topic_name: "/world/empty/model/Elkapod/link/leg1_FCP/sensor/contact/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS

- ros_topic_name: "/legs/leg2_fsr"
  gz_topic_name: "/world/empty/model/Elkapod/link/leg2_FCP/sensor/contact/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS

- ros_topic_name: "/legs/leg3_fsr"
  gz_topic_name: "/world/empty/model/Elkapod/link/leg3_FCP/sensor/contact/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS

- ros_topic_name: "/legs/leg4_fsr"
  gz_topic_name: "/world/empty/model/Elkapod/link/leg4_FCP/sensor/contact/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS

- ros_topic_name: "/legs/leg5_fsr"
  gz_topic_name: "/world/empty/model/Elkapod/link/leg5_FCP/sensor/contact/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS

- ros_topic_name: "/legs/leg6_fsr"
  gz_topic_name: "/world/empty/model/Elkapod/link/leg6_FCP/sensor/contact/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS

- ros_topic_name: "lidar_data_points"
  gz_topic_name: "lidar_data/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
  lazy: false

- ros_topic_name: "front_camera/camera_info"
  gz_topic_name: "front_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "front_camera/depth_image"
  gz_topic_name: "front_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "front_camera/image"
  gz_topic_name: "front_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "front_camera/points"
  gz_topic_name: "front_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS