controller_manager:
  ros__parameters:
    update_rate: 50

    hardware_components_initial_state:
      shutdown_on_initial_state_failure: true

    enforce_command_limits: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    elkapod_ik_controller:
      type: elkapod_ik_controller/ElkapodIKController

    passthrough_controller:          
      type: passthrough_controller/PassthroughController

    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

elkapod_ik_controller:
  ros__parameters:
    joints:
      - passthrough_controller/leg1_J1
      - passthrough_controller/leg1_J2
      - passthrough_controller/leg1_J3
      - passthrough_controller/leg2_J1
      - passthrough_controller/leg2_J2
      - passthrough_controller/leg2_J3
      - passthrough_controller/leg3_J1
      - passthrough_controller/leg3_J2
      - passthrough_controller/leg3_J3
      - passthrough_controller/leg4_J1
      - passthrough_controller/leg4_J2
      - passthrough_controller/leg4_J3
      - passthrough_controller/leg5_J1
      - passthrough_controller/leg5_J2
      - passthrough_controller/leg5_J3
      - passthrough_controller/leg6_J1
      - passthrough_controller/leg6_J2
      - passthrough_controller/leg6_J3

passthrough_controller:
  ros__parameters:
    interfaces:
      - leg1_J1/position
      - leg1_J2/position
      - leg1_J3/position
      - leg2_J1/position
      - leg2_J2/position
      - leg2_J3/position
      - leg3_J1/position
      - leg3_J2/position
      - leg3_J3/position
      - leg4_J1/position
      - leg4_J2/position
      - leg4_J3/position
      - leg5_J1/position
      - leg5_J2/position
      - leg5_J3/position
      - leg6_J1/position
      - leg6_J2/position
      - leg6_J3/position

imu_broadcaster:
  ros__parameters:
    type: imu_sensor_broadcaster/IMUSensorBroadcaster
    sensor_name: imu_sensor
    frame_id: imu_link
