elkapod_motion_manager:
  ros__parameters:
    base_height:
      default: 0.17
      min: 0.12
      max: 0.22
    leg_spacing:
      default: 0.175
      min: 0.1
      max: 0.25
    standing_up:
      base_height_waypoint: 0.1
      leg_spacing_waypoint: 0.25

    trajectory:
      frequency_hz: 20.0
    
