name: elkapod CI

on:
  push:
  pull_request:
    branches: ["main"]
    types: [opened, synchronized, reopened]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Ruff
        run: |
          pip install ruff
          ruff check . --select C4,SIM,TCH

  build:
    needs: linting
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hexapodbionik/elkapod_sim:latest

    steps:
      - name: Setup Workspace
        run: mkdir -p ros_ws/src

      - name: Checkout elkapod
        uses: actions/checkout@v4
        with:
          path: ros_ws/src/elkapod

      - name: Clone msgs
        run: |
          git clone https://github.com/HexapodBionik/elkapod_msgs.git -b main ros_ws/src/elkapod_msgs

      - name: Rosdep Update
        shell: bash
        run: |
          sudo apt update
          rosdep update
          cd ros_ws
          rosdep install --from-paths src --ignore-src -y --rosdistro jazzy

      - name: Build
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          cd ros_ws
          colcon build --symlink-install --cmake-args -DCMAKE_CXX_FLAGS="-Werror"